default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: emmon_api_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: emmon_api_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  #database: emmon_api
  uri: ENV['DATABASE_URL']
