default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: emmon_api_development

test:
  <<: *default
  database: emmon_api_test

production:
  <<: *default
  database: emmon_api
  username: <%= Rails.application.credentials.database['username'] %>
  password: <%= Rails.application.credentials.database['password'] %>
  host: <%= Rails.application.credentials.database['host'] %>
