default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: emmon_api_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: emmon_api_test

production:
  <<: *default
  #database: emmon_api
  url: <%= ENV['DATABASE_URL'] =>
